
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello_test?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa: 
    database: mysql 
      
#  jpa:
#      hibernate:
#        ddl-auto: create #ddl-auto:设为update表示每次都不会重新建表
#      show-sql: true
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO         
          dataSource:
            druid:
                URL: jdbc:mysql://localhost:3306/hello_test
                driver: com.mysql.jdbc.Driver
                maxConnections: 5
                password: 123456
                user: root             
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            dataSource: druid
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: JDBC
    #初始化表结构
    #jdbc:
      #initialize-schema: never
     

server:
  port: 9999
  
mybatis: 
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: com.swdegao.quartz.entity
   